### ISSUE TITLE
2. Configurar Docker para frontend y backend

### ISSUE THREAD

**Issue by AnaJiRo** [AnaJiRo/ProyectoDB#8]
# Planning- Gestor de Colonias Felinas

### 2. Configurar Docker para frontend y backend
- [x] Crear `Dockerfile` para React.
- [x] Crear `Dockerfile` para Django.
- [x] Crear `docker-compose.yml` con servicios: PostgreSQL, React, Django.
- [x] Verificar levantamiento conjunto con `docker-compose up`.

---
# 🧩  Crear y Configurar Docker para frontend y backend.

## 📁 1. Estructura básica del proyecto

Primero, crea estas carpetas y archivos en tu directorio del proyecto:
```bash
mkdir gestor-colonias
cd gestor-colonias

mkdir backend frontend

touch docker-compose.yml
touch backend/Dockerfile
touch backend/requirements.txt
touch frontend/Dockerfile
```
## ⚙️ 2. Archivos de configuración:

> Abre  la carpeta del proyecto en VS Code, así podrás editar fácilmente todos los archivos como docker-compose.yml, Dockerfile, etc.

### 🔧 Cómo abrirlo en VS Code:
Abre una terminal y navega a tu proyecto:

 ```bash
cd ~/ruta/a/gestor-colonias
```
Luego simplemente escribe:

```bash
code . 
```

 Esto abrirá VS Code en esa carpeta.

> 💡 Si code no te funciona en terminal, abre VS Code desde el menú y ve a: Archivo > Abrir Carpeta y selecciona la carpeta del proyecto.

### 📄 docker-compose.yml
**Pega aquí el contenido de configuración:** 
```yml
services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: colonias
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: django-backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_NAME=colonias
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
```

### 🐍 backend/requirements.txt
```txt
Django>=4.0
psycopg2-binary
djangorestframework
djangorestframework-simplejwt
django-cors-headers>=3.14
```
### 🐍 backend/Dockerfile

```Dockerfile
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
```
### ⚛️ frontend/Dockerfile

```Dockerfile
FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev", "--", "--host" ]
```

Luego dentro de `frontend/`, necesitarás tu proyecto de React. Puedes crear uno básico para comprobar que todo esta ok con este comando:

> Si no tienes npm (Node Package Manager) instalado todavía, que es necesario para crear y manejar proyectos React/Vite.

#### ✅  Instala Node.js + npm

Desde terminal en Ubuntu:

```bash
sudo apt update
sudo apt install nodejs npm -y
```

Luego verifica que esté bien instalado:

```bash
node -v
npm -v
```
#### ✅ Crear el proyecto React con Vite

Una vez tengas npm, ahora sí:

```bash
cd frontend
npm create vite@latest .
# Aceptas instalar el paquete (y)
# Selecciona Remove existing files and continue
# Selecciona React + typeScript
npm install
cd ..
```

![Image](https://github.com/user-attachments/assets/ec6b95c2-a2b2-4629-a293-68504960f4ab)
>  Selecciona Remove existing files and continue

![Image](https://github.com/user-attachments/assets/c26d6e02-714c-4711-b58f-376fc1deea81)

 Al realizar la instalación borramos el Dockerfile del frontend, por lo que habrá que crearlo de nuevo. 

![Image](https://github.com/user-attachments/assets/b5a25c25-a4e6-4720-a41a-e099e757ebb7)
> archivo eliminado

#### ✅ ¿Tengo que cambiar algo en el Dockerfile?

Como Vite expone por defecto el puerto 5173, puedes ajustar el EXPOSE y el docker-compose.yml.

#### 🔧 Actualiza frontend/Dockerfile:

```Dockerfile
FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
```

#### 🔧 Y en docker-compose.yml:

 ```yml
 frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network        ```
Con eso, entrarías a tu app desde:
```arduino
http://localhost:5173/
```

### ✅ 3. Construir y levantar los contenedores

Estando en el directorio raíz (gestor-colonias), ejecuta:

```bash
docker compose build
```
Después:

```bash
docker compose up
```

Esto descargará las imágenes necesarias como python:3.11, postgres:14 y node:18, y levantará los contenedores. Si todo va bien, deberíamos ver algo como:

- **PostgreSQL** escuchando en el puerto 5432
- **Django** sirviendo en localhost:8000
- **React** en localhost:3000

### 🧪 4. Verifica que todo esté corriendo

En otra terminal puedes correr:

```bash
docker compose ps
```

Y deberías ver los contenedores `postgres-db`, `django-backend` y `react-frontend` corriendo.

### 💡 Tips extra
Para entrar al contenedor de Django:

 ```bash
docker exec -it django-backend bash
```
Para aplicar migraciones por primera vez (dentro del backend):

```bash
docker exec -it django-backend python manage.py migrate
```

---
